language: java
sudo: false
jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
  - $HOME/.m2

install: true
script: mvn --projects '!diozero-provider-jdkdio10,!diozero-provider-jdkdio11,!diozero-imu-visualiser' clean compile package install
