language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - mvn --projects '!diozero-provider-jdkdio10,!diozero-provider-jdkdio11,!diozero-imu-visualiser' clean compile package install -DskipTests
