language: java
sudo: false
jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - DIOZERO_PROJECTS="!diozero-provider-jdkdio10,!diozero-provider-jdkdio11,!diozero-imu-visualiser"

install: true
script: mvn --projects '${DIOZERO_PROJECTS}' clean compile package install

#deploy:
#  on:
#    all-branches: true
#  provider: bintray
#  file: distribution/bintray.json
#  user: mattjlewis
#  key: $BINTRAY_API_KEY
