language: java
sudo: false
jdk:
  - oraclejdk8
os:
  - linux

cache:
  directories:
  - $HOME/.m2

install: true
script: mvn --projects '!diozero-provider-jdkdio10,!diozero-provider-jdkdio11,!diozero-imu-visualiser' clean compile package install

deploy:
  on:
    all-branches: true
  provider: bintray
  file: distribution/target/diozero-distribution-0.10-SNAPSHOT-bin.zip
  user: mattjlewis
  key: $BINTRAY_API_KEY
