site_name: diozero
site_url: rtd.diozero.com
copyright: Copyright &copy; 2016 Matt Lewis
google_analytics: ['UA-73764647-1', 'rtd.diozero.com']
pages:
- Home: index.md
- Digital Input Devices: DigitalInputDevices.md
